### ISSUE TITLE
KnowledgebaseManagers Meta Issue

### ISSUE THREAD

**Issue by kkaris** [gyorilab/indra_db#217]
_**NOTE:** this list is being updated as more sources are updated/fixed_

This issue keeps track of issues and updates related to knowledgebase managers.

- [ ] TAS: Need a new TAS update - TAS maintainer has been sent a request for update
- [ ] Signor: https://github.com/sorgerlab/indra/issues/1419
- [ ] Causal Bionet: https://github.com/sorgerlab/indra/issues/1420
- [x] BioGRID: _No update needed_
- [x] Pathway Commons: _No update needed_
- [ ] CTD: New data available
- [ ] DrugBank: New data available
- [x] VirHostNet: _No update needed_
- [ ] Phospho.ELM - Get ConnectionError to gilda web service after running a couple of thousand of calls
- [x] HPRD: https://github.com/sorgerlab/indra/issues/1421 - resolved: assumes local files
- [ ] BEL Large Corpus: Small Corpus node-link json is missing - https://github.com/cthoyt/selventa-knowledge/issues/8
- [x] Phosphosite Plus: New data available and copied to S3
- [ ] RLIMS-P: _check for sourcedata update_
- [ ] TRRUST: _check for sourcedata update_
- [ ] DGI: _might need update of BeautifulSoup4_
- [ ] CRoG: _check for sourcedata update_
- [ ] CONIB: _check for sourcedata update_
- [ ] UbiBrowser: https://github.com/sorgerlab/indra/issues/1418

**Comment by kkaris** [comment]
Related PR in indra: https://github.com/sorgerlab/indra/pull/1423

**Comment by kkaris** [comment]
Question for DGI:
I switched to using [no version in the call](https://github.com/gyorilab/indra_db/commit/47babfbd8f1253101c627d8ef9a00c054646436a) to `process_version()` in `indra.sources.dgi.api`. This does make BeautifulSoup4 a sub-dependency via the import and use of `bioversion`. If this is not desirable we can stick with hard coding the version instead, or looking up the latest version ourselves with e.g. `xml`'s `ElementTree` or other built-in module.
